name: ${{ values.app_name }}-cicd

on:
  push:
    paths:
      - 'src/**'
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    
      - name: Shorten commit hash
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::6}" >> $GITHUB_OUTPUT
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ '${{ secrets.DOCKERHUB_USERNAME }}' }}
          password: ${{ '${{ secrets.DOCKERHUB_TOKEN }}' }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: codetreelearners/${{ values.app_name }}:${{'${{ steps.vars.outputs.SHORT_SHA }}'}}
    outputs:
      IMAGE_TAG: ${{ '${{ steps.vars.outputs.SHORT_SHA }}' }}

  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Modify values.yaml with new image tag
        shell: bash
        run: |
          echo ${{ '${{ needs.ci.outputs.IMAGE_TAG }}' }}
          sudo apt-get update && sudo apt-get install -y yq
          yq -Yi '.image.tag = "${{ '${{ needs.ci.outputs.IMAGE_TAG }}' }}"' charts/${{values.app_name }}/values-${{ values.app_env }}.yaml

      - name: Commit and push changes to values.yaml
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update values.yaml with image tag to ${{ '${{ needs.ci.outputs.IMAGE_TAG }}' }}"

      - name: Install ArgoCD CLI
        run: |
          sudo curl -ksSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          sudo chmod +x argocd
          sudo mv argocd /usr/local/bin/
      
      - name: Argocd login
        shell: bash
        run: |
          argocd login argocd-server.argocd \
            --insecure \
            --grpc-web \
            --username admin \
            --password ${{'${{ secrets.ARGOCD_PASSWORD }}'}}

      - name: Argocd repo add
        shell: bash
        run: |
          repo="https://github.com/learners-code-tree/${{ values.app_name }}.git"
          # Check if the repo is already added, if not add it
          argocd repo list | grep -q $repo || argocd repo add $repo
          # check if the app is already added, if not add it
          argocd app get ${{ values.app_name }} || argocd app create ${{ values.app_name }} \
            --repo $repo \
            --path charts/${{ values.app_name }} \
            --dest-server https://kubernetes.default.svc \
            --dest-namespace ${{ values.app_env }} \
            --values values-${{ values.app_env }}.yaml \
            --revision main \
            --sync-policy manual \
            --sync-option CreateNamespace=true

      - name: Argocd app sync
        shell: bash
        run: |
          argocd app sync ${{ values.app_name }}
          argocd app wait ${{ values.app_name }} --timeout 180